/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const PrivacyPolicyLazyImport = createFileRoute('/privacy-policy')()
const PhotoboothLazyImport = createFileRoute('/photobooth')()
const PhotoStripPreviewLazyImport = createFileRoute('/photo-strip-preview')()
const FaqLazyImport = createFileRoute('/faq')()
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const PrivacyPolicyLazyRoute = PrivacyPolicyLazyImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/privacy-policy.lazy').then((d) => d.Route),
)

const PhotoboothLazyRoute = PhotoboothLazyImport.update({
  id: '/photobooth',
  path: '/photobooth',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/photobooth.lazy').then((d) => d.Route))

const PhotoStripPreviewLazyRoute = PhotoStripPreviewLazyImport.update({
  id: '/photo-strip-preview',
  path: '/photo-strip-preview',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/photo-strip-preview.lazy').then((d) => d.Route),
)

const FaqLazyRoute = FaqLazyImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/faq.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqLazyImport
      parentRoute: typeof rootRoute
    }
    '/photo-strip-preview': {
      id: '/photo-strip-preview'
      path: '/photo-strip-preview'
      fullPath: '/photo-strip-preview'
      preLoaderRoute: typeof PhotoStripPreviewLazyImport
      parentRoute: typeof rootRoute
    }
    '/photobooth': {
      id: '/photobooth'
      path: '/photobooth'
      fullPath: '/photobooth'
      preLoaderRoute: typeof PhotoboothLazyImport
      parentRoute: typeof rootRoute
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/faq': typeof FaqLazyRoute
  '/photo-strip-preview': typeof PhotoStripPreviewLazyRoute
  '/photobooth': typeof PhotoboothLazyRoute
  '/privacy-policy': typeof PrivacyPolicyLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/faq': typeof FaqLazyRoute
  '/photo-strip-preview': typeof PhotoStripPreviewLazyRoute
  '/photobooth': typeof PhotoboothLazyRoute
  '/privacy-policy': typeof PrivacyPolicyLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/about': typeof AboutLazyRoute
  '/faq': typeof FaqLazyRoute
  '/photo-strip-preview': typeof PhotoStripPreviewLazyRoute
  '/photobooth': typeof PhotoboothLazyRoute
  '/privacy-policy': typeof PrivacyPolicyLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/faq'
    | '/photo-strip-preview'
    | '/photobooth'
    | '/privacy-policy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/faq'
    | '/photo-strip-preview'
    | '/photobooth'
    | '/privacy-policy'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/faq'
    | '/photo-strip-preview'
    | '/photobooth'
    | '/privacy-policy'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AboutLazyRoute: typeof AboutLazyRoute
  FaqLazyRoute: typeof FaqLazyRoute
  PhotoStripPreviewLazyRoute: typeof PhotoStripPreviewLazyRoute
  PhotoboothLazyRoute: typeof PhotoboothLazyRoute
  PrivacyPolicyLazyRoute: typeof PrivacyPolicyLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AboutLazyRoute: AboutLazyRoute,
  FaqLazyRoute: FaqLazyRoute,
  PhotoStripPreviewLazyRoute: PhotoStripPreviewLazyRoute,
  PhotoboothLazyRoute: PhotoboothLazyRoute,
  PrivacyPolicyLazyRoute: PrivacyPolicyLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/about",
        "/faq",
        "/photo-strip-preview",
        "/photobooth",
        "/privacy-policy"
      ]
    },
    "/": {
      "filePath": "index.lazy.jsx"
    },
    "/about": {
      "filePath": "about.lazy.jsx"
    },
    "/faq": {
      "filePath": "faq.lazy.jsx"
    },
    "/photo-strip-preview": {
      "filePath": "photo-strip-preview.lazy.jsx"
    },
    "/photobooth": {
      "filePath": "photobooth.lazy.jsx"
    },
    "/privacy-policy": {
      "filePath": "privacy-policy.lazy.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
